In [4]:
from sklearn.preprocessing import label_binarize
import numpy as np

n_share = 4
label_all = np.array([0,1,2,1,2,0,3])
class_list = [i for i in range(n_share)]
Y_test = label_binarize(label_all, classes=[i for i in class_list])

print(Y_test)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]]
